### ISSUE TITLE
error: cannot find EFI directory

### ISSUE THREAD

**Issue by lkareeml** [mpolitzer/grub-iso-multiboot#2]
after following all steps
when performing the installation step 2.2 install grub & copy release files
after performing command
grub-install --boot-directory=/tmp/$LABEL/boot /dev/sdX
I get
Installing for x86_64-efi platform.
then error message
grub-install: error: cannot find EFI directory.
I tried to search problem on google, but had no luck, I am new to grub I don't understand how it works
I hope you help me soon,
Debian 11.2
USB 32GB

**Comment by mpolitzer** [comment]
Hi, thanks for taking a look at the project.
From what I know EFI uses a GPT partition table instead of a DOS one.
This project started using DOS partition so that the usbstick could still work on Windows, this might have changed, haven't tried a GPT partition table on windows in a while.

Specifically on the issue you are having. Could you confirm if you skipped step 1 (went directly to 2) and if you have a GPT or DOS partition table for your usbstick? 
On linux you can check by running this (not sure on MacOS nor Windows):
```
fdisk /dev/sdX
> print
> quit
```
There will be a line indicating it (in case of GPT):
`> Disklabel type: gpt`

**Comment by lmcarreiro** [comment]
Thanks for the project. I also had the same issue, and it happens in a DOS partition. I also tried to use `--no-uefi-secure-boot` and it also didn't work...

![image](https://user-images.githubusercontent.com/13019179/183291492-08a5fe49-dd0c-432e-ac06-d0163f404390.png)

**Comment by lmcarreiro** [comment]
btw, I was able to install using `--target=i386-pc`, but I'm not sure what is the impact of this... maybe it won't be bootable without turning EUFI off...

```
grub-install --target=i386-pc --boot-directory=/tmp/$LABEL/boot /dev/sdX

**Comment by lmcarreiro** [comment]
Not sure if it's the same, but I saw on this [other project](https://github.com/Jimmy-Z/grub-iso-boot) this alternative way to install grub on the usb drive:

1. Build bootx64.efi (this command will create the `bootx64.efi` file in the current directory):
```
grub-mkimage -o bootx64.efi -O x86_64-efi -p /boot/grub \
	boot linux linux16 chain normal configfile \
	part_gpt part_msdos fat iso9660 udf \
	test true keystatus loopback regexp probe \
	efi_gop efi_uga all_video gfxterm font \
	echo read help ls cat halt reboot
```
2. Copy bootx64.efi to (USB)/efi/boot/.

**Comment by mpolitzer** [comment]
That looks very promising.
I'll have a better look at it when I have some time.

**Comment by mpolitzer** [comment]
Latest version migrates to GPT + EFI.
